package manager.comment;

import static manager.exception.ManagerExceptionList.*;


public interface ClientComment {

    String RESET = "\u001B[0m";
    String FONT_RED = "\u001B[31m";
    String FONT_BLUE = "\u001B[34m";

    String SUCCESS = FONT_BLUE+"요청에 성공하였습니다."+RESET;
    String NO_COURSE_NUM_COMMENT = FONT_RED+ NO_COURSE_DATA.getMessage()+RESET;
    String STUDENT_NUM = FONT_RED+ NO_STUDENT.getMessage()+RESET;
    String DISCONNECTION = FONT_RED+"DB연결에 에러가 발생하였습니다."+RESET;
    String NO_DATA_MAJOR_COMMENT = FONT_RED+ NO_DATA_MAJOR.getMessage()+RESET;
    String VALIDATE_STUDENT_NUM_COMMENT = FONT_RED+ VALIDATE_STUDENT_NUM.getMessage()+RESET;
    String OVERLAP_STUDENT_ID_COMMENT = FONT_RED+ OVERLAP_STUDENT_ID.getMessage() +RESET;
    String OVERLAP_COURSE_NUM_COMMENT = FONT_RED+OVERLAP_COURSE_NUM.getMessage()+RESET;
    String NO_DATA_PREREQUISITE_COMMENT = FONT_RED+NO_DATA_PREREQUISITE.getMessage()+RESET;
    String OVER_COURSE_CREDIT_COMMENT = FONT_RED+OVER_COURSE_CREDIT.getMessage()+RESET;
    String VALIDATE_NUMBER_COMMENT = FONT_RED+VALIDATE_NUMBER.getMessage()+RESET;
    String ALREADY_ENROLMENT_COMMENT = FONT_RED+ALREADY_ENROLMENT.getMessage()+RESET;
    String ALREADY_COURSE_COMMENT = FONT_RED+ALREADY_COURSE.getMessage()+RESET;
    String NON_PREREQUISITE_COMMENT = FONT_RED+NON_PREREQUISITE.getMessage()+RESET;



    String STUDENT = "student";
}
